services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=praticando
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fpf2023
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}