# Generated by Django 5.2.5 on 2025-08-21 23:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('cep', models.CharField(db_column='tx_cep', max_length=8)),
                ('street', models.CharField(db_column='tx_street', max_length=120)),
                ('neighborhood', models.CharField(db_column='tx_neighborhood', max_length=120)),
                ('house_number', models.IntegerField(db_column='nb_house_number')),
                ('complement', models.CharField(db_column='tx_complement', max_length=120)),
                ('reference', models.CharField(db_column='tx_reference', max_length=120)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Adresses',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
                ('email', models.EmailField(db_column='tx_email', max_length=254)),
                ('cpf', models.CharField(db_column='tx_cpf', max_length=11)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('payment_type', models.CharField(db_column='tx_payment_type', max_length=120)),
            ],
            options={
                'verbose_name': 'Payment_type',
                'verbose_name_plural': 'Payment_types',
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('value', models.DecimalField(db_column='nb_amount', decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Finished')], db_column='tx_status', default=1)),
                ('delivery_deadline', models.DateTimeField(db_column='dt_delivery_deadline')),
                ('start_date', models.DateTimeField(db_column='dt_start_date')),
                ('end_date', models.DateTimeField(db_column='dt_end_date')),
                ('description', models.TextField(db_column='tx_description', max_length=240)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
                ('brand', models.ForeignKey(db_column='id_brand', on_delete=django.db.models.deletion.PROTECT, to='core.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('number', models.CharField(db_column='tx_number', max_length=12)),
                ('customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phone',
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('discount', models.DecimalField(db_column='nb_discount', decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(db_column='nb_total', decimal_places=2, max_digits=10)),
                ('method', models.ForeignKey(db_column='id_method', on_delete=django.db.models.deletion.PROTECT, to='core.method')),
                ('service', models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('year', models.IntegerField(db_column='nb_year', validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1500)])),
                ('type', models.IntegerField(choices=[(1, 'Car'), (2, 'Motorcycle'), (3, 'Truck')], db_column='nb_type', default=1)),
                ('color', models.CharField(db_column='tx_color')),
                ('license_plate', models.CharField(db_column='tx_license_plate', max_length=7)),
                ('km', models.IntegerField(db_column='nb_km', validators=[django.core.validators.MinValueValidator(0)])),
                ('car_model', models.ForeignKey(db_column='id_car_model', on_delete=django.db.models.deletion.PROTECT, to='core.carmodel')),
                ('customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(db_column='id_vehicle', on_delete=django.db.models.deletion.PROTECT, to='core.vehicle'),
        ),
    ]
