# Generated by Django 5.2.5 on 2025-08-29 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_city_alter_service_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
                ('email', models.EmailField(db_column='tx_email', max_length=254)),
                ('cpf', models.CharField(db_column='tx_cpf', max_length=11)),
                ('salary', models.DecimalField(db_column='nb_salary', decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'employer',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at')),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('position', models.CharField(db_column='tx_position', max_length=120)),
                ('employer', models.ForeignKey(db_column='id_employer', on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'position',
            },
        ),
    ]
